/**
 * Tailwind Design Tokens - Generated from Figma
 * DO NOT EDIT MANUALLY - Run `npm run build:tokens` to regenerate
 *
 * DARK MODE SUPPORT:
 * For components to properly respond to dark mode, use SEMANTIC tokens instead of primitives:
 *
 * ❌ DON'T: text-gray-700, bg-gray-50, border-gray-300, ring-gray-200
 * ✅ DO:    text-secondary, bg-secondary, border-primary, ring-border-secondary
 *
 * Semantic tokens use CSS variables that change with [data-theme="dark"].
 * Primitive color scales (gray-light, brand, error, etc.) are static values.
 *
 * See .cursor/rules/design-tokens.mdc for the full mapping reference.
 */

module.exports = {
  colors: {
  base: {
    white: '#ffffff',
    black: '#000000',
    transparent: 'rgba(255, 255, 255, 0.0000)'
  },
  'gray-light': {
    '25': '#fdfdfd',
    '50': '#fafafa',
    '100': '#f5f5f5',
    '200': '#e9eaeb',
    '300': '#d5d7da',
    '400': '#a4a7ae',
    '500': '#717680',
    '600': '#535862',
    '700': '#414651',
    '800': '#252b37',
    '900': '#181d27',
    '950': '#0a0d12'
  },
  'gray-dark-alpha': {
    '25': 'rgba(255, 255, 255, 0.9800)',
    '50': 'rgba(255, 255, 255, 0.9600)',
    '100': 'rgba(255, 255, 255, 0.9400)',
    '200': 'rgba(255, 255, 255, 0.9200)',
    '300': 'rgba(255, 255, 255, 0.8000)',
    '400': 'rgba(255, 255, 255, 0.5600)',
    '500': 'rgba(255, 255, 255, 0.5000)',
    '600': 'rgba(255, 255, 255, 0.3500)',
    '700': 'rgba(255, 255, 255, 0.1600)',
    '800': 'rgba(255, 255, 255, 0.0800)',
    '900': 'rgba(255, 255, 255, 0.0400)',
    '950': 'rgba(255, 255, 255, 0.0000)'
  },
  brand: {
    '25': '#fcfaff',
    '50': '#f9f5ff',
    '100': '#f4ebff',
    '200': '#e9d7fe',
    '300': '#d6bbfb',
    '400': '#b692f6',
    '500': '#9e77ed',
    '600': '#7f56d9',
    '700': '#6941c6',
    '800': '#53389e',
    '900': '#42307d',
    '950': '#2c1c5f'
  },
  error: {
    '25': '#fffbfa',
    '50': '#fef3f2',
    '100': '#fee4e2',
    '200': '#fecdca',
    '300': '#fda29b',
    '400': '#f97066',
    '500': '#f04438',
    '600': '#d92d20',
    '700': '#b42318',
    '800': '#912018',
    '900': '#7a271a',
    '950': '#55160c'
  },
  warning: {
    '25': '#fffcf5',
    '50': '#fffaeb',
    '100': '#fef0c7',
    '200': '#fedf89',
    '300': '#fec84b',
    '400': '#fdb022',
    '500': '#f79009',
    '600': '#dc6803',
    '700': '#b54708',
    '800': '#93370d',
    '900': '#7a2e0e',
    '950': '#4e1d09'
  },
  success: {
    '25': '#f6fef9',
    '50': '#ecfdf3',
    '100': '#dcfae6',
    '200': '#abefc6',
    '300': '#75e0a7',
    '400': '#47cd89',
    '500': '#17b26a',
    '600': '#079455',
    '700': '#067647',
    '800': '#085d3a',
    '900': '#074d31',
    '950': '#053321'
  },
  'gray-blue': {
    '25': '#fcfcfd',
    '50': '#f8f9fc',
    '100': '#eaecf5',
    '200': '#d5d9eb',
    '300': '#b3b8db',
    '400': '#717bbc',
    '500': '#4e5ba6',
    '600': '#3e4784',
    '700': '#363f72',
    '800': '#293056',
    '900': '#101323',
    '950': '#0d0f1c'
  },
  'gray-cool': {
    '25': '#fcfcfd',
    '50': '#f9f9fb',
    '100': '#eff1f5',
    '200': '#dcdfea',
    '300': '#b9c0d4',
    '400': '#7d89b0',
    '500': '#5d6b98',
    '600': '#4a5578',
    '700': '#404968',
    '800': '#30374f',
    '900': '#111322',
    '950': '#0e101b'
  },
  'gray-modern': {
    '25': '#fcfcfd',
    '50': '#f8fafc',
    '100': '#eef2f6',
    '200': '#e3e8ef',
    '300': '#cdd5df',
    '400': '#9aa4b2',
    '500': '#697586',
    '600': '#4b5565',
    '700': '#364152',
    '800': '#202939',
    '900': '#121926',
    '950': '#0d121c'
  },
  'gray-neutral': {
    '25': '#fcfcfd',
    '50': '#f9fafb',
    '100': '#f3f4f6',
    '200': '#e5e7eb',
    '300': '#d2d6db',
    '400': '#9da4ae',
    '500': '#6c737f',
    '600': '#4d5761',
    '700': '#384250',
    '800': '#1f2a37',
    '900': '#111927',
    '950': '#0d121c'
  },
  'gray-iron': {
    '25': '#fcfcfc',
    '50': '#fafafa',
    '100': '#f4f4f5',
    '200': '#e4e4e7',
    '300': '#d1d1d6',
    '400': '#a0a0ab',
    '500': '#70707b',
    '600': '#51525c',
    '700': '#3f3f46',
    '800': '#26272b',
    '900': '#1a1a1e',
    '950': '#131316'
  },
  'gray-true': {
    '25': '#fcfcfc',
    '50': '#f7f7f7',
    '100': '#f5f5f5',
    '200': '#e5e5e5',
    '300': '#d6d6d6',
    '400': '#a3a3a3',
    '500': '#737373',
    '600': '#525252',
    '700': '#424242',
    '800': '#292929',
    '900': '#141414',
    '950': '#0f0f0f'
  },
  'gray-warm': {
    '25': '#fdfdfc',
    '50': '#fafaf9',
    '100': '#f5f5f4',
    '200': '#e7e5e4',
    '300': '#d7d3d0',
    '400': '#a9a29d',
    '500': '#79716b',
    '600': '#57534e',
    '700': '#44403c',
    '800': '#292524',
    '900': '#1c1917',
    '950': '#171412'
  },
  moss: {
    '25': '#fafdf7',
    '50': '#f5fbee',
    '100': '#e6f4d7',
    '200': '#ceeab0',
    '300': '#acdc79',
    '400': '#86cb3c',
    '500': '#669f2a',
    '600': '#4f7a21',
    '700': '#3f621a',
    '800': '#335015',
    '900': '#2b4212',
    '950': '#1a280b'
  },
  'green-light': {
    '25': '#fafef5',
    '50': '#f3fee7',
    '100': '#e3fbcc',
    '200': '#d0f8ab',
    '300': '#a6ef67',
    '400': '#85e13a',
    '500': '#66c61c',
    '600': '#4ca30d',
    '700': '#3b7c0f',
    '800': '#326212',
    '900': '#2b5314',
    '950': '#15290a'
  },
  green: {
    '25': '#f6fef9',
    '50': '#edfcf2',
    '100': '#d3f8df',
    '200': '#aaf0c4',
    '300': '#73e2a3',
    '400': '#3ccb7f',
    '500': '#16b364',
    '600': '#099250',
    '700': '#087443',
    '800': '#095c37',
    '900': '#084c2e',
    '950': '#052e1c'
  },
  teal: {
    '25': '#f6fefc',
    '50': '#f0fdf9',
    '100': '#ccfbef',
    '200': '#99f6e0',
    '300': '#5fe9d0',
    '400': '#2ed3b7',
    '500': '#15b79e',
    '600': '#0e9384',
    '700': '#107569',
    '800': '#125d56',
    '900': '#134e48',
    '950': '#0a2926'
  },
  cyan: {
    '25': '#f5feff',
    '50': '#ecfdff',
    '100': '#cff9fe',
    '200': '#a5f0fc',
    '300': '#67e3f9',
    '400': '#22ccee',
    '500': '#06aed4',
    '600': '#088ab2',
    '700': '#0e7090',
    '800': '#155b75',
    '900': '#164c63',
    '950': '#0d2d3a'
  },
  'blue-light': {
    '25': '#f5fbff',
    '50': '#f0f9ff',
    '100': '#e0f2fe',
    '200': '#b9e6fe',
    '300': '#7cd4fd',
    '400': '#36bffa',
    '500': '#0ba5ec',
    '600': '#0086c9',
    '700': '#026aa2',
    '800': '#065986',
    '900': '#0b4a6f',
    '950': '#062c41'
  },
  blue: {
    '25': '#f5faff',
    '50': '#eff8ff',
    '100': '#d1e9ff',
    '200': '#b2ddff',
    '300': '#84caff',
    '400': '#53b1fd',
    '500': '#2e90fa',
    '600': '#1570ef',
    '700': '#175cd3',
    '800': '#1849a9',
    '900': '#194185',
    '950': '#102a56'
  },
  'blue-dark': {
    '25': '#f5f8ff',
    '50': '#eff4ff',
    '100': '#d1e0ff',
    '200': '#b2ccff',
    '300': '#84adff',
    '400': '#528bff',
    '500': '#2970ff',
    '600': '#155eef',
    '700': '#004eeb',
    '800': '#0040c1',
    '900': '#00359e',
    '950': '#002266'
  },
  indigo: {
    '25': '#f5f8ff',
    '50': '#eef4ff',
    '100': '#e0eaff',
    '200': '#c7d7fe',
    '300': '#a4bcfd',
    '400': '#8098f9',
    '500': '#6172f3',
    '600': '#444ce7',
    '700': '#3538cd',
    '800': '#2d31a6',
    '900': '#2d3282',
    '950': '#1f235b'
  },
  violet: {
    '25': '#fbfaff',
    '50': '#f5f3ff',
    '100': '#ece9fe',
    '200': '#ddd6fe',
    '300': '#c3b5fd',
    '400': '#a48afb',
    '500': '#875bf7',
    '600': '#7839ee',
    '700': '#6927da',
    '800': '#5720b7',
    '900': '#491c96',
    '950': '#2e125e'
  },
  purple: {
    '25': '#fafaff',
    '50': '#f4f3ff',
    '100': '#ebe9fe',
    '200': '#d9d6fe',
    '300': '#bdb4fe',
    '400': '#9b8afb',
    '500': '#7a5af8',
    '600': '#6938ef',
    '700': '#5925dc',
    '800': '#4a1fb8',
    '900': '#3e1c96',
    '950': '#27115f'
  },
  fuchsia: {
    '25': '#fefaff',
    '50': '#fdf4ff',
    '100': '#fbe8ff',
    '200': '#f6d0fe',
    '300': '#eeaafd',
    '400': '#e478fa',
    '500': '#d444f1',
    '600': '#ba24d5',
    '700': '#9f1ab1',
    '800': '#821890',
    '900': '#6f1877',
    '950': '#47104c'
  },
  pink: {
    '25': '#fef6fb',
    '50': '#fdf2fa',
    '100': '#fce7f6',
    '200': '#fcceee',
    '300': '#faa7e0',
    '400': '#f670c7',
    '500': '#ee46bc',
    '600': '#dd2590',
    '700': '#c11574',
    '800': '#9e165f',
    '900': '#851651',
    '950': '#4e0d30'
  },
  'rosé': {
    '25': '#fff5f6',
    '50': '#fff1f3',
    '100': '#ffe4e8',
    '200': '#fecdd6',
    '300': '#fea3b4',
    '400': '#fd6f8e',
    '500': '#f63d68',
    '600': '#e31b54',
    '700': '#c01048',
    '800': '#a11043',
    '900': '#89123e',
    '950': '#510b24'
  },
  'orange-dark': {
    '25': '#fff9f5',
    '50': '#fff4ed',
    '100': '#ffe6d5',
    '200': '#ffd6ae',
    '300': '#ff9c66',
    '400': '#ff692e',
    '500': '#ff4405',
    '600': '#e62e05',
    '700': '#bc1b06',
    '800': '#97180c',
    '900': '#771a0d',
    '950': '#57130a'
  },
  orange: {
    '25': '#fefaf5',
    '50': '#fef6ee',
    '100': '#fdead7',
    '200': '#f9dbaf',
    '300': '#f7b27a',
    '400': '#f38744',
    '500': '#ef6820',
    '600': '#e04f16',
    '700': '#b93815',
    '800': '#932f19',
    '900': '#772917',
    '950': '#511c10'
  },
  yellow: {
    '25': '#fefdf0',
    '50': '#fefbe8',
    '100': '#fef7c3',
    '200': '#feee95',
    '300': '#fde272',
    '400': '#fac515',
    '500': '#eaaa08',
    '600': '#ca8504',
    '700': '#a15c07',
    '800': '#854a0e',
    '900': '#713b12',
    '950': '#542c0d'
  },
  'gray-dark': {
    '25': '#fafafa',
    '50': '#f7f7f7',
    '100': '#f0f0f1',
    '200': '#ececed',
    '300': '#cecfd2',
    '400': '#94979c',
    '500': '#85888e',
    '600': '#61656c',
    '700': '#373a41',
    '800': '#22262f',
    '900': '#13161b',
    '950': '#0c0e12'
  },
  text: {
    primary: 'var(--color-text-primary)',
    'primary-on-brand': 'var(--color-text-primary-on-brand)',
    secondary: 'var(--color-text-secondary)',
    'secondary-hover': 'var(--color-text-secondary-hover)',
    'secondary-on-brand': 'var(--color-text-secondary-on-brand)',
    tertiary: 'var(--color-text-tertiary)',
    'tertiary-hover': 'var(--color-text-tertiary-hover)',
    'tertiary-on-brand': 'var(--color-text-tertiary-on-brand)',
    quaternary: 'var(--color-text-quaternary)',
    'quaternary-on-brand': 'var(--color-text-quaternary-on-brand)',
    white: 'var(--color-text-white)',
    disabled: 'var(--color-text-disabled)',
    placeholder: 'var(--color-text-placeholder)',
    'placeholder-subtle': 'var(--color-text-placeholder-subtle)',
    'brand-primary': 'var(--color-text-brand-primary)',
    'brand-secondary': 'var(--color-text-brand-secondary)',
    'brand-secondary-hover': 'var(--color-text-brand-secondary-hover)',
    'brand-tertiary': 'var(--color-text-brand-tertiary)',
    'brand-tertiary-alt': 'var(--color-text-brand-tertiary-alt)',
    'error-primary': 'var(--color-text-error-primary)',
    'error-primary-hover': 'var(--color-text-error-primary-hover)',
    'warning-primary': 'var(--color-text-warning-primary)',
    'success-primary': 'var(--color-text-success-primary)'
  },
  border: {
    primary: 'var(--color-border-primary)',
    secondary: 'var(--color-border-secondary)',
    'secondary-alt': 'var(--color-border-secondary-alt)',
    tertiary: 'var(--color-border-tertiary)',
    disabled: 'var(--color-border-disabled)',
    'disabled-subtle': 'var(--color-border-disabled-subtle)',
    brand: 'var(--color-border-brand)',
    'brand-alt': 'var(--color-border-brand-alt)',
    error: 'var(--color-border-error)',
    'error-subtle': 'var(--color-border-error-subtle)'
  },
  fg: {
    primary: 'var(--color-fg-primary)',
    secondary: 'var(--color-fg-secondary)',
    'secondary-hover': 'var(--color-fg-secondary-hover)',
    tertiary: 'var(--color-fg-tertiary)',
    'tertiary-hover': 'var(--color-fg-tertiary-hover)',
    quaternary: 'var(--color-fg-quaternary)',
    'quaternary-hover': 'var(--color-fg-quaternary-hover)',
    white: 'var(--color-fg-white)',
    disabled: 'var(--color-fg-disabled)',
    'disabled-subtle': 'var(--color-fg-disabled-subtle)',
    'brand-primary': 'var(--color-fg-brand-primary)',
    'brand-primary-alt': 'var(--color-fg-brand-primary-alt)',
    'brand-secondary': 'var(--color-fg-brand-secondary)',
    'brand-secondary-alt': 'var(--color-fg-brand-secondary-alt)',
    'brand-secondary-hover': 'var(--color-fg-brand-secondary-hover)',
    'error-primary': 'var(--color-fg-error-primary)',
    'error-secondary': 'var(--color-fg-error-secondary)',
    'warning-primary': 'var(--color-fg-warning-primary)',
    'warning-secondary': 'var(--color-fg-warning-secondary)',
    'success-primary': 'var(--color-fg-success-primary)',
    'success-secondary': 'var(--color-fg-success-secondary)'
  },
  bg: {
    primary: 'var(--color-bg-primary)',
    'primary-alt': 'var(--color-bg-primary-alt)',
    'primary-hover': 'var(--color-bg-primary-hover)',
    'primary-solid': 'var(--color-bg-primary-solid)',
    secondary: 'var(--color-bg-secondary)',
    'secondary-alt': 'var(--color-bg-secondary-alt)',
    'secondary-hover': 'var(--color-bg-secondary-hover)',
    'secondary-subtle': 'var(--color-bg-secondary-subtle)',
    'secondary-solid': 'var(--color-bg-secondary-solid)',
    tertiary: 'var(--color-bg-tertiary)',
    quaternary: 'var(--color-bg-quaternary)',
    active: 'var(--color-bg-active)',
    disabled: 'var(--color-bg-disabled)',
    'disabled-subtle': 'var(--color-bg-disabled-subtle)',
    overlay: 'var(--color-bg-overlay)',
    'brand-primary': 'var(--color-bg-brand-primary)',
    'brand-primary-alt': 'var(--color-bg-brand-primary-alt)',
    'brand-secondary': 'var(--color-bg-brand-secondary)',
    'brand-solid': 'var(--color-bg-brand-solid)',
    'brand-solid-hover': 'var(--color-bg-brand-solid-hover)',
    'brand-section': 'var(--color-bg-brand-section)',
    'brand-section-subtle': 'var(--color-bg-brand-section-subtle)',
    'error-primary': 'var(--color-bg-error-primary)',
    'error-secondary': 'var(--color-bg-error-secondary)',
    'error-solid': 'var(--color-bg-error-solid)',
    'error-solid-hover': 'var(--color-bg-error-solid-hover)',
    'warning-primary': 'var(--color-bg-warning-primary)',
    'warning-secondary': 'var(--color-bg-warning-secondary)',
    'warning-solid': 'var(--color-bg-warning-solid)',
    'success-primary': 'var(--color-bg-success-primary)',
    'success-secondary': 'var(--color-bg-success-secondary)',
    'success-solid': 'var(--color-bg-success-solid)'
  },
  primary: {
    '25': '#fcfaff',
    '50': '#f9f5ff',
    '100': '#f4ebff',
    '200': '#e9d7fe',
    '300': '#d6bbfb',
    '400': '#b692f6',
    '500': '#9e77ed',
    '600': '#7f56d9',
    '700': '#6941c6',
    '800': '#53389e',
    '900': '#42307d',
    '950': '#2c1c5f'
  },
  destructive: {
    '25': '#fffbfa',
    '50': '#fef3f2',
    '100': '#fee4e2',
    '200': '#fecdca',
    '300': '#fda29b',
    '400': '#f97066',
    '500': '#f04438',
    '600': '#d92d20',
    '700': '#b42318',
    '800': '#912018',
    '900': '#7a271a',
    '950': '#55160c'
  }
},

  // Unified semantic colors for ALL color utilities (ring, fill, stroke, divide, etc.)
  // Use these with: ring-border-primary, stroke-fg-primary, fill-bg-primary, etc.
  semanticColors: {
  'text-primary': 'var(--color-text-primary)',
  'text-primary-on-brand': 'var(--color-text-primary-on-brand)',
  'text-secondary': 'var(--color-text-secondary)',
  'text-secondary-hover': 'var(--color-text-secondary-hover)',
  'text-secondary-on-brand': 'var(--color-text-secondary-on-brand)',
  'text-tertiary': 'var(--color-text-tertiary)',
  'text-tertiary-hover': 'var(--color-text-tertiary-hover)',
  'text-tertiary-on-brand': 'var(--color-text-tertiary-on-brand)',
  'text-quaternary': 'var(--color-text-quaternary)',
  'text-quaternary-on-brand': 'var(--color-text-quaternary-on-brand)',
  'text-white': 'var(--color-text-white)',
  'text-disabled': 'var(--color-text-disabled)',
  'text-placeholder': 'var(--color-text-placeholder)',
  'text-placeholder-subtle': 'var(--color-text-placeholder-subtle)',
  'text-brand-primary': 'var(--color-text-brand-primary)',
  'text-brand-secondary': 'var(--color-text-brand-secondary)',
  'text-brand-secondary-hover': 'var(--color-text-brand-secondary-hover)',
  'text-brand-tertiary': 'var(--color-text-brand-tertiary)',
  'text-brand-tertiary-alt': 'var(--color-text-brand-tertiary-alt)',
  'text-error-primary': 'var(--color-text-error-primary)',
  'text-error-primary-hover': 'var(--color-text-error-primary-hover)',
  'text-warning-primary': 'var(--color-text-warning-primary)',
  'text-success-primary': 'var(--color-text-success-primary)',
  'border-primary': 'var(--color-border-primary)',
  'border-secondary': 'var(--color-border-secondary)',
  'border-secondary-alt': 'var(--color-border-secondary-alt)',
  'border-tertiary': 'var(--color-border-tertiary)',
  'border-disabled': 'var(--color-border-disabled)',
  'border-disabled-subtle': 'var(--color-border-disabled-subtle)',
  'border-brand': 'var(--color-border-brand)',
  'border-brand-alt': 'var(--color-border-brand-alt)',
  'border-error': 'var(--color-border-error)',
  'border-error-subtle': 'var(--color-border-error-subtle)',
  'fg-primary': 'var(--color-fg-primary)',
  'fg-secondary': 'var(--color-fg-secondary)',
  'fg-secondary-hover': 'var(--color-fg-secondary-hover)',
  'fg-tertiary': 'var(--color-fg-tertiary)',
  'fg-tertiary-hover': 'var(--color-fg-tertiary-hover)',
  'fg-quaternary': 'var(--color-fg-quaternary)',
  'fg-quaternary-hover': 'var(--color-fg-quaternary-hover)',
  'fg-white': 'var(--color-fg-white)',
  'fg-disabled': 'var(--color-fg-disabled)',
  'fg-disabled-subtle': 'var(--color-fg-disabled-subtle)',
  'fg-brand-primary': 'var(--color-fg-brand-primary)',
  'fg-brand-primary-alt': 'var(--color-fg-brand-primary-alt)',
  'fg-brand-secondary': 'var(--color-fg-brand-secondary)',
  'fg-brand-secondary-alt': 'var(--color-fg-brand-secondary-alt)',
  'fg-brand-secondary-hover': 'var(--color-fg-brand-secondary-hover)',
  'fg-error-primary': 'var(--color-fg-error-primary)',
  'fg-error-secondary': 'var(--color-fg-error-secondary)',
  'fg-warning-primary': 'var(--color-fg-warning-primary)',
  'fg-warning-secondary': 'var(--color-fg-warning-secondary)',
  'fg-success-primary': 'var(--color-fg-success-primary)',
  'fg-success-secondary': 'var(--color-fg-success-secondary)',
  'bg-primary': 'var(--color-bg-primary)',
  'bg-primary-alt': 'var(--color-bg-primary-alt)',
  'bg-primary-hover': 'var(--color-bg-primary-hover)',
  'bg-primary-solid': 'var(--color-bg-primary-solid)',
  'bg-secondary': 'var(--color-bg-secondary)',
  'bg-secondary-alt': 'var(--color-bg-secondary-alt)',
  'bg-secondary-hover': 'var(--color-bg-secondary-hover)',
  'bg-secondary-subtle': 'var(--color-bg-secondary-subtle)',
  'bg-secondary-solid': 'var(--color-bg-secondary-solid)',
  'bg-tertiary': 'var(--color-bg-tertiary)',
  'bg-quaternary': 'var(--color-bg-quaternary)',
  'bg-active': 'var(--color-bg-active)',
  'bg-disabled': 'var(--color-bg-disabled)',
  'bg-disabled-subtle': 'var(--color-bg-disabled-subtle)',
  'bg-overlay': 'var(--color-bg-overlay)',
  'bg-brand-primary': 'var(--color-bg-brand-primary)',
  'bg-brand-primary-alt': 'var(--color-bg-brand-primary-alt)',
  'bg-brand-secondary': 'var(--color-bg-brand-secondary)',
  'bg-brand-solid': 'var(--color-bg-brand-solid)',
  'bg-brand-solid-hover': 'var(--color-bg-brand-solid-hover)',
  'bg-brand-section': 'var(--color-bg-brand-section)',
  'bg-brand-section-subtle': 'var(--color-bg-brand-section-subtle)',
  'bg-error-primary': 'var(--color-bg-error-primary)',
  'bg-error-secondary': 'var(--color-bg-error-secondary)',
  'bg-error-solid': 'var(--color-bg-error-solid)',
  'bg-error-solid-hover': 'var(--color-bg-error-solid-hover)',
  'bg-warning-primary': 'var(--color-bg-warning-primary)',
  'bg-warning-secondary': 'var(--color-bg-warning-secondary)',
  'bg-warning-solid': 'var(--color-bg-warning-solid)',
  'bg-success-primary': 'var(--color-bg-success-primary)',
  'bg-success-secondary': 'var(--color-bg-success-secondary)',
  'bg-success-solid': 'var(--color-bg-success-solid)',
  'effects-focus-rings-focus-ring': 'var(--color-effects-focus-rings-focus-ring)',
  'effects-focus-rings-focus-ring-error': 'var(--color-effects-focus-rings-focus-ring-error)',
  'effects-shadows-shadow-xs': 'var(--color-effects-shadows-shadow-xs)',
  'effects-shadows-shadow-sm-01': 'var(--color-effects-shadows-shadow-sm-01)',
  'effects-shadows-shadow-sm-02': 'var(--color-effects-shadows-shadow-sm-02)',
  'effects-shadows-shadow-md-01': 'var(--color-effects-shadows-shadow-md-01)',
  'effects-shadows-shadow-md-02': 'var(--color-effects-shadows-shadow-md-02)',
  'effects-shadows-shadow-lg-01': 'var(--color-effects-shadows-shadow-lg-01)',
  'effects-shadows-shadow-lg-02': 'var(--color-effects-shadows-shadow-lg-02)',
  'effects-shadows-shadow-lg-03': 'var(--color-effects-shadows-shadow-lg-03)',
  'effects-shadows-shadow-xl-01': 'var(--color-effects-shadows-shadow-xl-01)',
  'effects-shadows-shadow-xl-02': 'var(--color-effects-shadows-shadow-xl-02)',
  'effects-shadows-shadow-xl-03': 'var(--color-effects-shadows-shadow-xl-03)',
  'effects-shadows-shadow-2xl-01': 'var(--color-effects-shadows-shadow-2xl-01)',
  'effects-shadows-shadow-2xl-02': 'var(--color-effects-shadows-shadow-2xl-02)',
  'effects-shadows-shadow-3xl-01': 'var(--color-effects-shadows-shadow-3xl-01)',
  'effects-shadows-shadow-3xl-02': 'var(--color-effects-shadows-shadow-3xl-02)',
  'effects-shadows-shadow-skeumorphic-inner': 'var(--color-effects-shadows-shadow-skeumorphic-inner)',
  'effects-shadows-shadow-skeumorphic-inner-border': 'var(--color-effects-shadows-shadow-skeumorphic-inner-border)',
  'effects-portfolio-mockups-shadow-main-centre-md': 'var(--color-effects-portfolio-mockups-shadow-main-centre-md)',
  'effects-portfolio-mockups-shadow-main-centre-lg': 'var(--color-effects-portfolio-mockups-shadow-main-centre-lg)',
  'effects-portfolio-mockups-shadow-overlay-lg': 'var(--color-effects-portfolio-mockups-shadow-overlay-lg)',
  'effects-portfolio-mockups-shadow-grid-md': 'var(--color-effects-portfolio-mockups-shadow-grid-md)',
  'alpha-white-10': 'var(--color-alpha-white-10)',
  'alpha-white-20': 'var(--color-alpha-white-20)',
  'alpha-white-30': 'var(--color-alpha-white-30)',
  'alpha-white-40': 'var(--color-alpha-white-40)',
  'alpha-white-50': 'var(--color-alpha-white-50)',
  'alpha-white-60': 'var(--color-alpha-white-60)',
  'alpha-white-70': 'var(--color-alpha-white-70)',
  'alpha-white-80': 'var(--color-alpha-white-80)',
  'alpha-white-90': 'var(--color-alpha-white-90)',
  'alpha-white-100': 'var(--color-alpha-white-100)',
  'alpha-black-10': 'var(--color-alpha-black-10)',
  'alpha-black-20': 'var(--color-alpha-black-20)',
  'alpha-black-30': 'var(--color-alpha-black-30)',
  'alpha-black-40': 'var(--color-alpha-black-40)',
  'alpha-black-50': 'var(--color-alpha-black-50)',
  'alpha-black-60': 'var(--color-alpha-black-60)',
  'alpha-black-70': 'var(--color-alpha-black-70)',
  'alpha-black-80': 'var(--color-alpha-black-80)',
  'alpha-black-90': 'var(--color-alpha-black-90)',
  'alpha-black-100': 'var(--color-alpha-black-100)',
  'utility-gray-utility-gray-50': 'var(--color-utility-gray-utility-gray-50)',
  'utility-gray-utility-gray-100': 'var(--color-utility-gray-utility-gray-100)',
  'utility-gray-utility-gray-200': 'var(--color-utility-gray-utility-gray-200)',
  'utility-gray-utility-gray-300': 'var(--color-utility-gray-utility-gray-300)',
  'utility-gray-utility-gray-400': 'var(--color-utility-gray-utility-gray-400)',
  'utility-gray-utility-gray-500': 'var(--color-utility-gray-utility-gray-500)',
  'utility-gray-utility-gray-600': 'var(--color-utility-gray-utility-gray-600)',
  'utility-gray-utility-gray-700': 'var(--color-utility-gray-utility-gray-700)',
  'utility-gray-utility-gray-800': 'var(--color-utility-gray-utility-gray-800)',
  'utility-gray-utility-gray-900': 'var(--color-utility-gray-utility-gray-900)',
  'utility-brand-utility-brand-50': 'var(--color-utility-brand-utility-brand-50)',
  'utility-brand-utility-brand-50-alt': 'var(--color-utility-brand-utility-brand-50-alt)',
  'utility-brand-utility-brand-100': 'var(--color-utility-brand-utility-brand-100)',
  'utility-brand-utility-brand-100-alt': 'var(--color-utility-brand-utility-brand-100-alt)',
  'utility-brand-utility-brand-200': 'var(--color-utility-brand-utility-brand-200)',
  'utility-brand-utility-brand-200-alt': 'var(--color-utility-brand-utility-brand-200-alt)',
  'utility-brand-utility-brand-300': 'var(--color-utility-brand-utility-brand-300)',
  'utility-brand-utility-brand-300-alt': 'var(--color-utility-brand-utility-brand-300-alt)',
  'utility-brand-utility-brand-400': 'var(--color-utility-brand-utility-brand-400)',
  'utility-brand-utility-brand-400-alt': 'var(--color-utility-brand-utility-brand-400-alt)',
  'utility-brand-utility-brand-500': 'var(--color-utility-brand-utility-brand-500)',
  'utility-brand-utility-brand-500-alt': 'var(--color-utility-brand-utility-brand-500-alt)',
  'utility-brand-utility-brand-600': 'var(--color-utility-brand-utility-brand-600)',
  'utility-brand-utility-brand-600-alt': 'var(--color-utility-brand-utility-brand-600-alt)',
  'utility-brand-utility-brand-700': 'var(--color-utility-brand-utility-brand-700)',
  'utility-brand-utility-brand-700-alt': 'var(--color-utility-brand-utility-brand-700-alt)',
  'utility-brand-utility-brand-800': 'var(--color-utility-brand-utility-brand-800)',
  'utility-brand-utility-brand-800-alt': 'var(--color-utility-brand-utility-brand-800-alt)',
  'utility-brand-utility-brand-900': 'var(--color-utility-brand-utility-brand-900)',
  'utility-brand-utility-brand-900-alt': 'var(--color-utility-brand-utility-brand-900-alt)',
  'utility-error-utility-error-50': 'var(--color-utility-error-utility-error-50)',
  'utility-error-utility-error-100': 'var(--color-utility-error-utility-error-100)',
  'utility-error-utility-error-200': 'var(--color-utility-error-utility-error-200)',
  'utility-error-utility-error-300': 'var(--color-utility-error-utility-error-300)',
  'utility-error-utility-error-400': 'var(--color-utility-error-utility-error-400)',
  'utility-error-utility-error-500': 'var(--color-utility-error-utility-error-500)',
  'utility-error-utility-error-600': 'var(--color-utility-error-utility-error-600)',
  'utility-error-utility-error-700': 'var(--color-utility-error-utility-error-700)',
  'utility-warning-utility-warning-50': 'var(--color-utility-warning-utility-warning-50)',
  'utility-warning-utility-warning-100': 'var(--color-utility-warning-utility-warning-100)',
  'utility-warning-utility-warning-200': 'var(--color-utility-warning-utility-warning-200)',
  'utility-warning-utility-warning-300': 'var(--color-utility-warning-utility-warning-300)',
  'utility-warning-utility-warning-400': 'var(--color-utility-warning-utility-warning-400)',
  'utility-warning-utility-warning-500': 'var(--color-utility-warning-utility-warning-500)',
  'utility-warning-utility-warning-600': 'var(--color-utility-warning-utility-warning-600)',
  'utility-warning-utility-warning-700': 'var(--color-utility-warning-utility-warning-700)',
  'utility-success-utility-success-50': 'var(--color-utility-success-utility-success-50)',
  'utility-success-utility-success-100': 'var(--color-utility-success-utility-success-100)',
  'utility-success-utility-success-200': 'var(--color-utility-success-utility-success-200)',
  'utility-success-utility-success-300': 'var(--color-utility-success-utility-success-300)',
  'utility-success-utility-success-400': 'var(--color-utility-success-utility-success-400)',
  'utility-success-utility-success-500': 'var(--color-utility-success-utility-success-500)',
  'utility-success-utility-success-600': 'var(--color-utility-success-utility-success-600)',
  'utility-success-utility-success-700': 'var(--color-utility-success-utility-success-700)',
  'utility-gray-blue-utility-gray-blue-50': 'var(--color-utility-gray-blue-utility-gray-blue-50)',
  'utility-gray-blue-utility-gray-blue-100': 'var(--color-utility-gray-blue-utility-gray-blue-100)',
  'utility-gray-blue-utility-gray-blue-200': 'var(--color-utility-gray-blue-utility-gray-blue-200)',
  'utility-gray-blue-utility-gray-blue-300': 'var(--color-utility-gray-blue-utility-gray-blue-300)',
  'utility-gray-blue-utility-gray-blue-400': 'var(--color-utility-gray-blue-utility-gray-blue-400)',
  'utility-gray-blue-utility-gray-blue-500': 'var(--color-utility-gray-blue-utility-gray-blue-500)',
  'utility-gray-blue-utility-gray-blue-600': 'var(--color-utility-gray-blue-utility-gray-blue-600)',
  'utility-gray-blue-utility-gray-blue-700': 'var(--color-utility-gray-blue-utility-gray-blue-700)',
  'utility-green-utility-green-50': 'var(--color-utility-green-utility-green-50)',
  'utility-green-utility-green-100': 'var(--color-utility-green-utility-green-100)',
  'utility-green-utility-green-200': 'var(--color-utility-green-utility-green-200)',
  'utility-green-utility-green-300': 'var(--color-utility-green-utility-green-300)',
  'utility-green-utility-green-400': 'var(--color-utility-green-utility-green-400)',
  'utility-green-utility-green-500': 'var(--color-utility-green-utility-green-500)',
  'utility-green-utility-green-600': 'var(--color-utility-green-utility-green-600)',
  'utility-green-utility-green-700': 'var(--color-utility-green-utility-green-700)',
  'utility-blue-light-utility-blue-light-50': 'var(--color-utility-blue-light-utility-blue-light-50)',
  'utility-blue-light-utility-blue-light-100': 'var(--color-utility-blue-light-utility-blue-light-100)',
  'utility-blue-light-utility-blue-light-200': 'var(--color-utility-blue-light-utility-blue-light-200)',
  'utility-blue-light-utility-blue-light-300': 'var(--color-utility-blue-light-utility-blue-light-300)',
  'utility-blue-light-utility-blue-light-400': 'var(--color-utility-blue-light-utility-blue-light-400)',
  'utility-blue-light-utility-blue-light-500': 'var(--color-utility-blue-light-utility-blue-light-500)',
  'utility-blue-light-utility-blue-light-600': 'var(--color-utility-blue-light-utility-blue-light-600)',
  'utility-blue-light-utility-blue-light-700': 'var(--color-utility-blue-light-utility-blue-light-700)',
  'utility-blue-utility-blue-50': 'var(--color-utility-blue-utility-blue-50)',
  'utility-blue-utility-blue-100': 'var(--color-utility-blue-utility-blue-100)',
  'utility-blue-utility-blue-200': 'var(--color-utility-blue-utility-blue-200)',
  'utility-blue-utility-blue-300': 'var(--color-utility-blue-utility-blue-300)',
  'utility-blue-utility-blue-400': 'var(--color-utility-blue-utility-blue-400)',
  'utility-blue-utility-blue-500': 'var(--color-utility-blue-utility-blue-500)',
  'utility-blue-utility-blue-600': 'var(--color-utility-blue-utility-blue-600)',
  'utility-blue-utility-blue-700': 'var(--color-utility-blue-utility-blue-700)',
  'utility-blue-dark-utility-blue-dark-50': 'var(--color-utility-blue-dark-utility-blue-dark-50)',
  'utility-blue-dark-utility-blue-dark-100': 'var(--color-utility-blue-dark-utility-blue-dark-100)',
  'utility-blue-dark-utility-blue-dark-200': 'var(--color-utility-blue-dark-utility-blue-dark-200)',
  'utility-blue-dark-utility-blue-dark-300': 'var(--color-utility-blue-dark-utility-blue-dark-300)',
  'utility-blue-dark-utility-blue-dark-400': 'var(--color-utility-blue-dark-utility-blue-dark-400)',
  'utility-blue-dark-utility-blue-dark-500': 'var(--color-utility-blue-dark-utility-blue-dark-500)',
  'utility-blue-dark-utility-blue-dark-600': 'var(--color-utility-blue-dark-utility-blue-dark-600)',
  'utility-blue-dark-utility-blue-dark-700': 'var(--color-utility-blue-dark-utility-blue-dark-700)',
  'utility-indigo-utility-indigo-50': 'var(--color-utility-indigo-utility-indigo-50)',
  'utility-indigo-utility-indigo-100': 'var(--color-utility-indigo-utility-indigo-100)',
  'utility-indigo-utility-indigo-200': 'var(--color-utility-indigo-utility-indigo-200)',
  'utility-indigo-utility-indigo-300': 'var(--color-utility-indigo-utility-indigo-300)',
  'utility-indigo-utility-indigo-400': 'var(--color-utility-indigo-utility-indigo-400)',
  'utility-indigo-utility-indigo-500': 'var(--color-utility-indigo-utility-indigo-500)',
  'utility-indigo-utility-indigo-600': 'var(--color-utility-indigo-utility-indigo-600)',
  'utility-indigo-utility-indigo-700': 'var(--color-utility-indigo-utility-indigo-700)',
  'utility-purple-utility-purple-50': 'var(--color-utility-purple-utility-purple-50)',
  'utility-purple-utility-purple-100': 'var(--color-utility-purple-utility-purple-100)',
  'utility-purple-utility-purple-200': 'var(--color-utility-purple-utility-purple-200)',
  'utility-purple-utility-purple-300': 'var(--color-utility-purple-utility-purple-300)',
  'utility-purple-utility-purple-400': 'var(--color-utility-purple-utility-purple-400)',
  'utility-purple-utility-purple-500': 'var(--color-utility-purple-utility-purple-500)',
  'utility-purple-utility-purple-600': 'var(--color-utility-purple-utility-purple-600)',
  'utility-purple-utility-purple-700': 'var(--color-utility-purple-utility-purple-700)',
  'utility-fuchsia-utility-fuchsia-50': 'var(--color-utility-fuchsia-utility-fuchsia-50)',
  'utility-fuchsia-utility-fuchsia-100': 'var(--color-utility-fuchsia-utility-fuchsia-100)',
  'utility-fuchsia-utility-fuchsia-200': 'var(--color-utility-fuchsia-utility-fuchsia-200)',
  'utility-fuchsia-utility-fuchsia-300': 'var(--color-utility-fuchsia-utility-fuchsia-300)',
  'utility-fuchsia-utility-fuchsia-400': 'var(--color-utility-fuchsia-utility-fuchsia-400)',
  'utility-fuchsia-utility-fuchsia-500': 'var(--color-utility-fuchsia-utility-fuchsia-500)',
  'utility-fuchsia-utility-fuchsia-600': 'var(--color-utility-fuchsia-utility-fuchsia-600)',
  'utility-fuchsia-utility-fuchsia-700': 'var(--color-utility-fuchsia-utility-fuchsia-700)',
  'utility-pink-utility-pink-50': 'var(--color-utility-pink-utility-pink-50)',
  'utility-pink-utility-pink-100': 'var(--color-utility-pink-utility-pink-100)',
  'utility-pink-utility-pink-200': 'var(--color-utility-pink-utility-pink-200)',
  'utility-pink-utility-pink-300': 'var(--color-utility-pink-utility-pink-300)',
  'utility-pink-utility-pink-400': 'var(--color-utility-pink-utility-pink-400)',
  'utility-pink-utility-pink-500': 'var(--color-utility-pink-utility-pink-500)',
  'utility-pink-utility-pink-600': 'var(--color-utility-pink-utility-pink-600)',
  'utility-pink-utility-pink-700': 'var(--color-utility-pink-utility-pink-700)',
  'utility-orange-dark-utility-orange-dark-50': 'var(--color-utility-orange-dark-utility-orange-dark-50)',
  'utility-orange-dark-utility-orange-dark-100': 'var(--color-utility-orange-dark-utility-orange-dark-100)',
  'utility-orange-dark-utility-orange-dark-200': 'var(--color-utility-orange-dark-utility-orange-dark-200)',
  'utility-orange-dark-utility-orange-dark-300': 'var(--color-utility-orange-dark-utility-orange-dark-300)',
  'utility-orange-dark-utility-orange-dark-400': 'var(--color-utility-orange-dark-utility-orange-dark-400)',
  'utility-orange-dark-utility-orange-dark-500': 'var(--color-utility-orange-dark-utility-orange-dark-500)',
  'utility-orange-dark-utility-orange-dark-600': 'var(--color-utility-orange-dark-utility-orange-dark-600)',
  'utility-orange-dark-utility-orange-dark-700': 'var(--color-utility-orange-dark-utility-orange-dark-700)',
  'utility-orange-utility-orange-50': 'var(--color-utility-orange-utility-orange-50)',
  'utility-orange-utility-orange-100': 'var(--color-utility-orange-utility-orange-100)',
  'utility-orange-utility-orange-200': 'var(--color-utility-orange-utility-orange-200)',
  'utility-orange-utility-orange-300': 'var(--color-utility-orange-utility-orange-300)',
  'utility-orange-utility-orange-400': 'var(--color-utility-orange-utility-orange-400)',
  'utility-orange-utility-orange-500': 'var(--color-utility-orange-utility-orange-500)',
  'utility-orange-utility-orange-600': 'var(--color-utility-orange-utility-orange-600)',
  'utility-orange-utility-orange-700': 'var(--color-utility-orange-utility-orange-700)',
  'utility-yellow-utility-yellow-50': 'var(--color-utility-yellow-utility-yellow-50)',
  'utility-yellow-utility-yellow-100': 'var(--color-utility-yellow-utility-yellow-100)',
  'utility-yellow-utility-yellow-200': 'var(--color-utility-yellow-utility-yellow-200)',
  'utility-yellow-utility-yellow-300': 'var(--color-utility-yellow-utility-yellow-300)',
  'utility-yellow-utility-yellow-400': 'var(--color-utility-yellow-utility-yellow-400)',
  'utility-yellow-utility-yellow-500': 'var(--color-utility-yellow-utility-yellow-500)',
  'utility-yellow-utility-yellow-600': 'var(--color-utility-yellow-utility-yellow-600)',
  'utility-yellow-utility-yellow-700': 'var(--color-utility-yellow-utility-yellow-700)',
  'components-app-store-badges-app-store-badge-border': 'var(--color-components-app-store-badges-app-store-badge-border)',
  'components-avatars-avatar-styles-bg-neutral': 'var(--color-components-avatars-avatar-styles-bg-neutral)',
  'components-buttons-button-primary-icon': 'var(--color-components-buttons-button-primary-icon)',
  'components-buttons-button-primary-icon-hover': 'var(--color-components-buttons-button-primary-icon-hover)',
  'components-buttons-button-destructive-primary-icon': 'var(--color-components-buttons-button-destructive-primary-icon)',
  'components-buttons-button-destructive-primary-icon-hover': 'var(--color-components-buttons-button-destructive-primary-icon-hover)',
  'components-footers-footer-button-fg': 'var(--color-components-footers-footer-button-fg)',
  'components-footers-footer-button-fg-hover': 'var(--color-components-footers-footer-button-fg-hover)',
  'components-icons-icons-icon-fg-brand': 'var(--color-components-icons-icons-icon-fg-brand)',
  'components-icons-icons-icon-fg-brand-on-brand': 'var(--color-components-icons-icons-icon-fg-brand-on-brand)',
  'components-icons-featured-icons-featured-icon-light-fg-brand': 'var(--color-components-icons-featured-icons-featured-icon-light-fg-brand)',
  'components-icons-featured-icons-featured-icon-light-fg-gray': 'var(--color-components-icons-featured-icons-featured-icon-light-fg-gray)',
  'components-icons-featured-icons-featured-icon-light-fg-error': 'var(--color-components-icons-featured-icons-featured-icon-light-fg-error)',
  'components-icons-featured-icons-featured-icon-light-fg-warning': 'var(--color-components-icons-featured-icons-featured-icon-light-fg-warning)',
  'components-icons-featured-icons-featured-icon-light-fg-success': 'var(--color-components-icons-featured-icons-featured-icon-light-fg-success)',
  'components-mockups-screen-mockup-border': 'var(--color-components-mockups-screen-mockup-border)',
  'components-sliders-slider-handle-bg': 'var(--color-components-sliders-slider-handle-bg)',
  'components-sliders-slider-handle-border': 'var(--color-components-sliders-slider-handle-border)',
  'components-toggles-toggle-button-fg-disabled': 'var(--color-components-toggles-toggle-button-fg-disabled)',
  'components-toggles-toggle-border': 'var(--color-components-toggles-toggle-border)',
  'components-toggles-toggle-slim-border-pressed': 'var(--color-components-toggles-toggle-slim-border-pressed)',
  'components-toggles-toggle-slim-border-pressed-hover': 'var(--color-components-toggles-toggle-slim-border-pressed-hover)',
  'components-tooltips-tooltip-supporting-text': 'var(--color-components-tooltips-tooltip-supporting-text)',
  'components-text-editor-text-editor-icon-fg': 'var(--color-components-text-editor-text-editor-icon-fg)',
  'components-text-editor-text-editor-icon-fg-active': 'var(--color-components-text-editor-text-editor-icon-fg-active)'
},

  // Utility-specific semantic colors (legacy - for backward compatibility)
  // These allow text-primary, bg-primary, border-primary to use semantic CSS variables
  textColor: {
  primary: 'var(--color-text-primary)',
  'primary-on-brand': 'var(--color-text-primary-on-brand)',
  secondary: 'var(--color-text-secondary)',
  'secondary-hover': 'var(--color-text-secondary-hover)',
  'secondary-on-brand': 'var(--color-text-secondary-on-brand)',
  tertiary: 'var(--color-text-tertiary)',
  'tertiary-hover': 'var(--color-text-tertiary-hover)',
  'tertiary-on-brand': 'var(--color-text-tertiary-on-brand)',
  quaternary: 'var(--color-text-quaternary)',
  'quaternary-on-brand': 'var(--color-text-quaternary-on-brand)',
  white: 'var(--color-text-white)',
  disabled: 'var(--color-text-disabled)',
  placeholder: 'var(--color-text-placeholder)',
  'placeholder-subtle': 'var(--color-text-placeholder-subtle)',
  'brand-primary': 'var(--color-text-brand-primary)',
  'brand-secondary': 'var(--color-text-brand-secondary)',
  'brand-secondary-hover': 'var(--color-text-brand-secondary-hover)',
  'brand-tertiary': 'var(--color-text-brand-tertiary)',
  'brand-tertiary-alt': 'var(--color-text-brand-tertiary-alt)',
  'error-primary': 'var(--color-text-error-primary)',
  'error-primary-hover': 'var(--color-text-error-primary-hover)',
  'warning-primary': 'var(--color-text-warning-primary)',
  'success-primary': 'var(--color-text-success-primary)',
  'fg-primary': 'var(--color-fg-primary)',
  'fg-secondary': 'var(--color-fg-secondary)',
  'fg-secondary-hover': 'var(--color-fg-secondary-hover)',
  'fg-tertiary': 'var(--color-fg-tertiary)',
  'fg-tertiary-hover': 'var(--color-fg-tertiary-hover)',
  'fg-quaternary': 'var(--color-fg-quaternary)',
  'fg-quaternary-hover': 'var(--color-fg-quaternary-hover)',
  'fg-white': 'var(--color-fg-white)',
  'fg-disabled': 'var(--color-fg-disabled)',
  'fg-disabled-subtle': 'var(--color-fg-disabled-subtle)',
  'fg-brand-primary': 'var(--color-fg-brand-primary)',
  'fg-brand-primary-alt': 'var(--color-fg-brand-primary-alt)',
  'fg-brand-secondary': 'var(--color-fg-brand-secondary)',
  'fg-brand-secondary-alt': 'var(--color-fg-brand-secondary-alt)',
  'fg-brand-secondary-hover': 'var(--color-fg-brand-secondary-hover)',
  'fg-error-primary': 'var(--color-fg-error-primary)',
  'fg-error-secondary': 'var(--color-fg-error-secondary)',
  'fg-warning-primary': 'var(--color-fg-warning-primary)',
  'fg-warning-secondary': 'var(--color-fg-warning-secondary)',
  'fg-success-primary': 'var(--color-fg-success-primary)',
  'fg-success-secondary': 'var(--color-fg-success-secondary)',
  'tooltip-supporting-text': 'var(--color-components-tooltips-tooltip-supporting-text)'
},

  backgroundColor: {
  primary: 'var(--color-bg-primary)',
  'primary-alt': 'var(--color-bg-primary-alt)',
  'primary-hover': 'var(--color-bg-primary-hover)',
  'primary-solid': 'var(--color-bg-primary-solid)',
  secondary: 'var(--color-bg-secondary)',
  'secondary-alt': 'var(--color-bg-secondary-alt)',
  'secondary-hover': 'var(--color-bg-secondary-hover)',
  'secondary-subtle': 'var(--color-bg-secondary-subtle)',
  'secondary-solid': 'var(--color-bg-secondary-solid)',
  tertiary: 'var(--color-bg-tertiary)',
  quaternary: 'var(--color-bg-quaternary)',
  active: 'var(--color-bg-active)',
  disabled: 'var(--color-bg-disabled)',
  'disabled-subtle': 'var(--color-bg-disabled-subtle)',
  overlay: 'var(--color-bg-overlay)',
  'brand-primary': 'var(--color-bg-brand-primary)',
  'brand-primary-alt': 'var(--color-bg-brand-primary-alt)',
  'brand-secondary': 'var(--color-bg-brand-secondary)',
  'brand-solid': 'var(--color-bg-brand-solid)',
  'brand-solid-hover': 'var(--color-bg-brand-solid-hover)',
  'brand-section': 'var(--color-bg-brand-section)',
  'brand-section-subtle': 'var(--color-bg-brand-section-subtle)',
  'error-primary': 'var(--color-bg-error-primary)',
  'error-secondary': 'var(--color-bg-error-secondary)',
  'error-solid': 'var(--color-bg-error-solid)',
  'error-solid-hover': 'var(--color-bg-error-solid-hover)',
  'warning-primary': 'var(--color-bg-warning-primary)',
  'warning-secondary': 'var(--color-bg-warning-secondary)',
  'warning-solid': 'var(--color-bg-warning-solid)',
  'success-primary': 'var(--color-bg-success-primary)',
  'success-secondary': 'var(--color-bg-success-secondary)',
  'success-solid': 'var(--color-bg-success-solid)'
},

  borderColor: {
  primary: 'var(--color-border-primary)',
  secondary: 'var(--color-border-secondary)',
  'secondary-alt': 'var(--color-border-secondary-alt)',
  tertiary: 'var(--color-border-tertiary)',
  disabled: 'var(--color-border-disabled)',
  'disabled-subtle': 'var(--color-border-disabled-subtle)',
  brand: 'var(--color-border-brand)',
  'brand-alt': 'var(--color-border-brand-alt)',
  error: 'var(--color-border-error)',
  'error-subtle': 'var(--color-border-error-subtle)'
},

  spacing: {
  '0': '0px',
  '1': '4px',
  '2': '8px',
  '3': '12px',
  '4': '16px',
  '5': '20px',
  '6': '24px',
  '8': '32px',
  '10': '40px',
  '12': '48px',
  '16': '64px',
  '20': '80px',
  '24': '96px',
  '32': '128px',
  '40': '160px',
  '48': '192px',
  '56': '224px',
  '64': '256px',
  '80': '320px',
  '96': '384px',
  '120': '480px',
  '140': '560px',
  '160': '640px',
  '180': '720px',
  '192': '768px',
  '256': '1024px',
  '320': '1280px',
  '360': '1440px',
  '400': '1600px',
  '480': '1920px',
  '0.5': '2px',
  '1.5': '6px',
  '2.5': '10px',
  '3.5': '14px'
},

  borderRadius: {
  none: '0px',
  xxs: '2px',
  xs: '4px',
  sm: '6px',
  md: '8px',
  lg: '10px',
  xl: '12px',
  '2xl': '16px',
  '3xl': '20px',
  '4xl': '24px',
  full: '9999px',
  DEFAULT: '4px'
},

  width: {
  auto: 'auto',
  full: '100%',
  screen: '100vw',
  svw: '100svw',
  lvw: '100lvw',
  dvw: '100dvw',
  min: 'min-content',
  max: 'max-content',
  fit: 'fit-content',
  xxs: '320px',
  xs: '384px',
  sm: '480px',
  md: '560px',
  lg: '640px',
  xl: '768px',
  '2xl': '1024px',
  '3xl': '1280px',
  '4xl': '1440px',
  '5xl': '1600px',
  '6xl': '1920px',
  'paragraph-max-width': '720px'
},

  // CSS intrinsic sizing values for height - Tailwind defaults that must be preserved
  height: {
    auto: 'auto',
    full: '100%',
    screen: '100vh',
    svh: '100svh',
    lvh: '100lvh',
    dvh: '100dvh',
    min: 'min-content',
    max: 'max-content',
    fit: 'fit-content',
  },

  // CSS intrinsic sizing values for min/max dimensions
  minWidth: {
    full: '100%',
    min: 'min-content',
    max: 'max-content',
    fit: 'fit-content',
  },

  maxWidth: {
  'container-padding-mobile': '16px',
  'container-padding-desktop': '32px',
  'container-max-width-desktop': '1280px'
},

  minHeight: {
    full: '100%',
    screen: '100vh',
    svh: '100svh',
    lvh: '100lvh',
    dvh: '100dvh',
    min: 'min-content',
    max: 'max-content',
    fit: 'fit-content',
  },

  maxHeight: {
    full: '100%',
    screen: '100vh',
    svh: '100svh',
    lvh: '100lvh',
    dvh: '100dvh',
    min: 'min-content',
    max: 'max-content',
    fit: 'fit-content',
  },

  fontSize: {
  xs: [
    '12px',
    {
      lineHeight: '18px'
    }
  ],
  sm: [
    '14px',
    {
      lineHeight: '20px'
    }
  ],
  md: [
    '16px',
    {
      lineHeight: '24px'
    }
  ],
  lg: [
    '18px',
    {
      lineHeight: '28px'
    }
  ],
  xl: [
    '20px',
    {
      lineHeight: '30px'
    }
  ],
  'display-xs': [
    '24px',
    {
      lineHeight: '32px'
    }
  ],
  'display-sm': [
    '30px',
    {
      lineHeight: '38px'
    }
  ],
  'display-md': [
    '36px',
    {
      lineHeight: '44px'
    }
  ],
  'display-lg': [
    '48px',
    {
      lineHeight: '60px'
    }
  ],
  'display-xl': [
    '60px',
    {
      lineHeight: '72px'
    }
  ],
  'display-2xl': [
    '72px',
    {
      lineHeight: '90px'
    }
  ]
},

  fontFamily: {
  display: [
    'Inter',
    'system-ui',
    'sans-serif'
  ],
  body: [
    'Inter',
    'system-ui',
    'sans-serif'
  ]
},

  fontWeight: {
  regular: '400',
  'regular-italic': '400',
  medium: '500',
  'medium-italic': '500',
  semibold: '600',
  'semibold-italic': '600',
  bold: '700',
  'bold-italic': '700'
},
};
